service: graphql-serverless

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: src/graphqlHandler.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
      - http:
          path: users  # New GET endpoint path
          method: get  # New GET method
          cors: true   # Enable CORS if needed

plugins:
  - serverless-offline  # Remove serverless-webpack

custom:
  serverless-offline:
    httpPort: 4000  # Custom port

resources:
  Resources:
    GraphQLApi:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: GraphQL API
